Zotero/Extensions/MD5+Url.swift

Using CryptoKit (part of all Apple platforms) allows us to avoid multiple warnings about how MD5 is deprecated in a cryptographic context and avoids the very un-Swifty C operations related to CommonCrypto. Getting Data from the URL is also simplified.

Simplify MD5 hash generation and avoid warnings

---

.gitmodules

This project has four dependencies linked as Git Submodules. Previously, two of these submodules were linked via https and two were linked via ssh. This pull request makes the minor modification of linking all submodules via https.
With the previous configuration, an initial clone and setup of the Zotero iOS repo would fail if the local computer did not have an SSH key associated with the user's GitHub account, even though the project and all submodules are open source and publicly published, and can therefore be cloned by an anonymous user. With the current setup, a user who encounters this needs to either manually modify the .gitmodules file to use https links, or install an SSH key in their Github account that is present on their local machine. By changing the project to link all …

Link all Git submodules via https

---

Zotero.xcodeproj/project.pbxproj

Previously, the project excluded arm64 processors when building for iOS Simulators. This change removes that exclusion so the project will build for the iOS Simulator on both Intel and Apple Silicon processors.
Apple recommends that projects [exclude architectures sparingly](https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon#Exclude-architectures-sparingly). The approach to exclude arm64 processors from simulator builds was in some cases expedient when Apple Silicon processors were new, a project's third party dependencies were shipping precompiled frameworks rather than source code, and those frameworks had not been updated to include support for the arm64 simulator. Where a project's developers were not using Apple Silicon machines, there …

Enable building for Apple Silicon simulator

---

Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailViewController.swift

At present when opening a doi.org link created from a DOI, the project is addingPercentEncoding to the DOI using the [.urlHostAllowed](https://developer.apple.com/documentation/foundation/nscharacterset/1416426-urlhostallowed) character set when it should be using the [.urlPathAllowed](https://developer.apple.com/documentation/foundation/nscharacterset/1416804-urlpathallowed) character set.
The effect is that a DOI string correctly stored as `10.1080/24735132.2022.2151776` is currently being encoded to `10.1080%2F24735132.2022.2151776` and thus passed to the webview as [https://doi.org/10.1080%2F24735132.2022.2151776](https://doi.org/10.1080%2F24735132.2022.2151776).
Because Webkit like all browsers is forgiving of percent encoding of path separators in URLs, this does not affect the …

Don’t percent encode valid slash character in DOIs

---

Zotero.xcodeproj/project.pbxproj
scripts/fetch_bundled_jsons.sh
scripts/licenses.sh
scripts/setup.sh

Hey guys, amazing work here 💪 
When the absolute path for the project directory contains unescaped characters, specifically whitespaces, the current setup always fails because of the way path "fragments" are rendered as different arguments. 
This is a small fix for such edge cases.

Fix setup for paths needing escaping

---

Zotero/Scenes/Detail/DetailCoordinator.swift

Created a quick fix, using proper navigation controller. Proper fix where standalone note is refactored into separate coordinator is included in tagfiltering branch

Fixed #645 tag picker appearing behind standalone note editor

---

Zotero/Scenes/Detail/PDF/Views/AnnotationsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

1. After testing this I noticed a reload wasn't happening because interface style changes do not have `updatedNotificationKeys`. I moved that change to its own scope and now I reload the whole section because an interface style change requires that. 
2. I moved the storeAnnotationPreviews to the annotation view controller.

reload whenever interface style changes

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/AnnotationPreviewController.swift
Zotero/Controllers/Architecture/Coordinator.swift
Zotero/Extensions/CoreGraphics+Extensions.swift
Zotero/Extensions/Localizable.swift
Zotero/Scenes/Detail/Annotation Popover/AnnotationPopoverCoordinator.swift
Zotero/Scenes/Detail/Annotation Popover/Views/AnnotationViewController.swift
Zotero/Scenes/Detail/CitationBibliographyExport/ViewModels/CitationBibliographyExportActionHandler.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationView.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewHeader.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationCell.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationsViewController.swift

closes #677 
* Adds share button in `AnnotationViewHeader` of image annotations, both in annotations in sidebar or selected annotation in document. When button is tapped it presents a `UIMenu` with 2 options, `Medium` & `Large`, corresponding to 300 & 600 PPI. Said options present a `UIActivityViewController`  for sharing the image (anchored to the share button). 
* Extends `AnnotationPreviewController` to allow rendering an image with an arbitrary size.
* Also adds some minor code improvements.
While this button will only be present for image annotations, we could easily extend the functionality for other types, e.g. to share a text snippet. The menu is built for the whole annotation, so it is easy to extend.
There are also some minor issues pending, noted as `TODO` items in the changes.

Share image annotation

---

Zotero/Controllers/Architecture/Coordinator.swift
Zotero/Scenes/AppCoordinator.swift
Zotero/Scenes/Detail/Annotation Filter Popover/AnnotationsFilterPopoverCoordinator.swift
Zotero/Scenes/Detail/Annotation Popover/AnnotationPopoverCoordinator.swift
Zotero/Scenes/Detail/CitationBibliographyExport/CitationBibliographyExportCoordinator.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/Items/ItemsFilterCoordinator.swift
Zotero/Scenes/Detail/Lookup/LookupCoordinator.swift
Zotero/Scenes/Detail/PDF/AnnotationEditCoordinator.swift
Zotero/Scenes/Detail/PDF/CreatorEditCoordinator.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/General/NoteEditorCoordinator.swift
Zotero/Scenes/Main/Views/MainViewController.swift
Zotero/Scenes/Master/Collection Editing/CollectionEditingCoordinator.swift
Zotero/Scenes/Master/MasterTopCoordinator.swift
Zotero/Scenes/Master/Settings/SettingsCoordinator.swift

I couldn't reproduce the crash myself, but obviously it happened that `navigationController` was deinitialized while `PDFCoordinator` instance was presented and when going back from PDF to previous screen the app would crash. Making `navigationController` in `Coordinator` protocol weak will solve this and potentially there may be user reports of UI issues which will point us in right direction.

Refactored Coordinator.navigationController to be weak instead of unowned

---

Zotero/Extensions/NSUserActivity+Activities.swift
Zotero/Scenes/AppCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Main/Views/MainViewController.swift
Zotero/Scenes/Master/MasterTopCoordinator.swift

closes #703 
Restores proper hierarchy for both iPhone & iPad.
Updates `Defaults.shared.selectedLibrary` & `Defaults.shared.selectedCollectionId` accordingly.
Tested cases, for both devices:
* open pdf, close app, launch app with restored state, pdf is shown, and selected collection should be the same
* open pdf, close app, share with extension to a different collection, launch app with restored state, pdf is shown, and selected collection should be the same
Easiest way to be certain that you get restoration of your previous state, is to close normally the app, restart simulator/device, launch the app again.

Show proper hierarchy when there is restored state

---

Zotero.xcodeproj/project.pbxproj
Zotero/Scenes/Detail/Annotation Popover/Views/HighlightEditCell.xib
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailAbstractEditContentView.xib
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailFieldMultilineEditContentView.xib
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailTitleContentView.xib
Zotero/Scenes/Detail/Lookup/Views/ManualLookupViewController.xib
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewTextView.swift
Zotero/Scenes/General/Views/TextKit1TextView.swift
Zotero/Scenes/General/Views/TextPreviewViewController.xib

closes #719
Subclasses UITextView to TextKit1TextView, to force use of TextKit 1. New class needs to be used only in other subclasses declaration (like `AnnotationTextView`) or in interface builder files.

Subclass UITextView to force use of TextKit 1

---

Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailViewController.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift
Zotero/Scenes/Detail/Lookup/LookupCoordinator.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Master/MasterTopCoordinator.swift

I added more logs for some basic UI actions such as opening PDF, selecting collection etc.

Added more logs for basic UI actions

---

Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/ShareableImage.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift

closes #725 
Source for annotation image to be shared is explicit, as otherwise AirDrop has a different behavior to the expected one.
Also improves preview of the shared image.

Improve shared annotation image generation

---

Zotero/Controllers/HtmlAttributedStringConverter.swift
ZoteroTests/HtmlAttributedStringConverterSpec.swift

May be relevant to https://forums.zotero.org/discussion/106722/ipad-why-my-zotero-in-ipad-crush-and-report-id-always-changing/p1

Fix HtmlAttributedStringConverter AttributedString to HTML conversion

---

Zotero/Scenes/Detail/Annotation Popover/Views/AnnotationViewController.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationView.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewHeader.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationsViewController.swift

* Fixes `AnnotationCell` setup crash, reported via AppStoreConnect analytics. Happens in an edge case, where `AnnotationsViewController` finds `nil` values in `weak` properties.
* Remove unused parameters to simplify code.

Fix AnnotationCell setup crash

---

ZShare/DbRequests/CreateBackendItemDbRequest.swift
ZShare/DbRequests/CreateItemWithAttachmentDbRequest.swift
Zotero/Controllers/Database/Requests/CreateTranslatedItemsDbRequest.swift
Zotero/Controllers/Database/Requests/MarkObjectsAsSyncedDbRequest.swift
Zotero/Controllers/Database/Requests/StoreItemsDbResponseRequest.swift
Zotero/Controllers/Sync/SyncActions/RevertLibraryFilesSyncAction.swift
Zotero/Controllers/Sync/SyncActions/RevertLibraryUpdatesSyncAction.swift
Zotero/Controllers/Sync/SyncBatchProcessor.swift
ZoteroTests/SyncActionsSpec.swift
ZoteroTests/WebDavControllerSpec.swift

Creators should be validated and item should not be stored during sync, but invalid creator can be ignored when adding an item through share extension.
Fixes #741

Improved validation of creators during sync

---

Zotero/Controllers/TranslatorsAndStylesController.swift
Zotero/Extensions/RegularExpression+Extensions.swift

Updated translator id parsing regex to include only proper translator ids

---

Zotero/Scenes/Detail/Items/Views/ItemsTableViewHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift

Don't open metadata on cell tap

---

Zotero/Controllers/Architecture/ViewModel.swift

As pointed out in https://github.com/zotero/zotero-ios/pull/733#issuecomment-1713615314 the `state` didn't get updated properly in `loadAttributedComment` because the reentrancy fix blocked out properly storing of state (`self.stateObservable.accept(state)` wasn't called). I switched from `BehaviorRelay` to `PublishSubject. Now I can control when to send notifications to observers and state is stored in the `ViewModel` directly, which makes more sense anyway. So RxSwift and Combine implementations are now the same.

Fix re-entrancy fix regression

---

Zotero/Scenes/Detail/Annotation Filter Popover/Views/AnnotationsFilterViewController.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailCollectionViewHandler.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailTitleContentView.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsToolbarController.swift
Zotero/Scenes/Detail/Items/Views/ItemsFilterViewController.swift
Zotero/Scenes/Detail/Items/Views/ItemsTableViewHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift
Zotero/Scenes/Main/Views/MainViewController.swift
Zotero/Scenes/Master/MasterContainerViewController.swift
Zotero/Scenes/Master/MasterCoordinator.swift
Zotero/Scenes/Master/MasterTopCoordinator.swift
Zotero/Scenes/Master/TagFiltering/Views/TagFilterViewController.swift

Modifies `MasterContainerViewController` to inherit from `UINavigationController`. This allows split view controller to merge/separate navigation stacks when it collapses/expands. 
`MasterContainerViewController` is used for both iPhone and iPad, with these differences:
* in iPhone the bottom controller is not created
* for iPhones Pro Max and Plus, the default behavior of showing a split view controller in landscape is kept, but without the bottom controller
So the case that was previously
`UIDevice.current.userInterfaceIdiom == .pad`
becomes (in most cases)
`traitCollection.horizontalSizeClass == .regular && UIDevice.current.userInterfaceIdiom == .pad`
and the case that was previously
`UIDevice.current.userInterfaceIdiom == .phone`
becomes (in most cases) …

Fix size class transition issues

---

Zotero/Scenes/Detail/Items/Models/ItemsAction.swift
Zotero/Scenes/Detail/Items/Models/ItemsState.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsTableViewHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift

There is some weird (possibly Apple) bug, where caching a `NSAttributedString` with a `.font` attribute causes the label to ignore the dynamic type change.
Fixes #768

Fixed dynamic type issue with items list title

---

Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift
Zotero/Scenes/Master/Collections/Views/CollectionsViewController.swift
Zotero/Scenes/Master/MasterContainerViewController.swift

Remove old style of search bar, replace with iOS default style

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/API/Alamofire+RxSwift.swift
Zotero/Controllers/Background Uploader/BackgroundUploadObserver.swift
Zotero/Controllers/Sync/SyncActions/AuthorizeUploadSyncAction.swift
Zotero/Controllers/Sync/SyncController.swift
Zotero/Controllers/WebDAV/WebDavController.swift
Zotero/Extensions/Localizable.swift
Zotero/Models/Sync/SyncErrors.swift
Zotero/Scenes/General/Views/SyncToolbarController.swift

Don't cancel sync on webdav request failure

---

Zotero/Controllers/Debugging/ApiLogger.swift
Zotero/Scenes/AppCoordinator.swift

I was able to reproduce and fix the issue on iOS 15.5 simulator. Unfortunately it was issue in CocoaLumberjack, the crash pointed to `String(format: storage.format, arguments: storage.args)` `EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`. So I just limited the size of string to 5k characters.
Fixes #785

Fixed CocoaLumberjack crashes on older iOSes

---

Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationView.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationCell.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationsViewController.swift

We had some crashes in `AnnotationCell.prepareForReuse()` because the `disposeBag` was `nil`.

Fixed missing dispose bag in AnnotationCell

---

Zotero/Models/Database/Database.swift
Zotero/Scenes/Detail/Annotation Popover/Views/AnnotationPageLabelViewController.swift
Zotero/Scenes/Detail/Annotation Popover/Views/TextFieldCell.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewHeader.swift

Closes #781
The same annotation page label max length as in the macOS client is used, but since the API does allow a larger limit, we may want to revisit that.

Improve annotation page label

---

Zotero/Controllers/Debugging/ApiLogger.swift

Disable api response logging for iOS <17

---

.github/workflows/run-tests.yml
Zotero/Scenes/Master/Collections/Views/CollectionsViewController.swift
Zotero/Scenes/Master/Libraries/Views/LibrariesViewController.swift
Zotero/Scenes/Master/MasterContainerViewController.swift

https://forums.zotero.org/discussion/108739/ios-tag-pane-prevents-scrolling-collections/
Adjusts additional safe area insets for interested view controllers, so they can always scroll to bottom of their content, regardless of the bottom sheet height.

Improve master container bottom additional safe area inset

---

Zotero/Extensions/String+Extensions.swift

There are numerous crashes with no real info in them, but they all seem to be processing translators in the background and the crash points to `mimeTypeFromExtension` being called, even though it's not specifically mentioned that it crashes there. We encountered similar issue with `extensionFromMimeType` a long time ago, so it might be worth a try to hard code most used values.

Hardcoded most used extension and mimetypes as possible crash fix

---

Zotero/Extensions/UIView+Extensions.swift
Zotero/Extensions/UIViewController+Extensions.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

* Fixes warning due to deprecation
* Correctly detects key window if multiple scenes of Zotero are in the screen (e.g. in iPad side-by-side)
(Will also be useful for proper multiple open items logic in the side-by-side case)

Improve current scene key window detection

---

Zotero.xcodeproj/project.pbxproj
ci_scripts/ci_post_clone.sh
ci_scripts/ci_post_xcodebuild.sh
ci_scripts/ci_pre_xcodebuild.sh
ci_scripts/generate_jtw_token.py
scripts/push_build

* Uses App Store Connect API to set version in post clone script. It uses current released version, and increments it according to version bump type.
* Tags the commit used for the build with an annotated version tag `<version>-<build>`. (Reminder, the build numbers themselves are handled by Xcode Cloud.
* Adds TestFlight message in post build script. Uses standard text, and then logs branch (if available), commit hash, and commit message.
A workflow using these script needs to have these environment variables set:
* app_store_connect_key_id
* zotero_app_id
* app_store_connect_api_key
* app_store_connect_issuer_id
`scripts/push_build` can be called to trigger an Xcode Cloud build by setting a trigger tag (not annotated, but we can change it), that decides the version bump type.
Those have …

Improve Xcode Cloud CI

---

Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/AnnotationConverter.swift
Zotero/Controllers/TextConverter.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

* Improves copied text from PDF documents by glueing hyphenated words in new lines and removing new lines.
* Improves annotation text by by glueing hyphenated before certain new lines are removed.
Improvement mentioned in this [forum discussion](https://forums.zotero.org/discussion/109222/ios-pdf-reader-improvement-request)
With some info from from https://github.com/zotero/zotero-ios/issues/308
~- [ ] Also add database migration for annotation text if needed.~

Improve text conversion for copying and highlighting from PDF documents

---

ci_scripts/ci_post_clone.sh

Update MARKETING_VERSION instead of CFBundleShortVersionString in CI post clone script, as the latter is also used for tagging the commit used in the build.

Fix CI MARKETING_VERSION

---

Zotero/Scenes/Detail/PDF/PDFCoordinator.swift

Fixes issue in https://forums.zotero.org/discussion/109983/ipados-17-2-zotero-beta-1-0-25-crash-when-searching-in-pdf-cmd-f
If the document screen is restored without a navigation bar, then the navigation item of the document view controller is not yet utilized by the navigaton controller. Hence, the bar button item used as the source for the search popover, is not part of the view hierarchy. Since search can be shown via external keyboard, with combination `command+F`, to be on the safe side, if the navigation bar is hidden, we use a source view and rect instead.

Fix document search source when navigation bar is hidden

---

Zotero/Controllers/HtmlAttributedStringConverter.swift
ZoteroTests/HtmlAttributedStringConverterSpec.swift

When emojis with a combined grapheme cluster are used, the conversion fails, because `NSAttributedString.length` doesn't take this into account. 
`AttributedString.characters.count` has the expected value, so we could also switch to that, if there is no other reason not to.

Fix HtmlAttributedStringConverter emoji support

---

Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

When the app state is restored to an open PDF document with a visible annotation toolbar, sometimes, due to the use of the extra `UIWindow` for the smoother instant presentation, there is not yet a `foregroundActive` connected scene, so `statusBarHeight` is set to `0`, messing up the annotation toolbar placement.
You can reproduce this by:
- opening a PDF document
- show annotation toolbar
- kill the app
- launch app again (open document should be restored)
Fix moves the computation in `viewDidLoad` that allows an easier way to access the `statusBarManager`.
Also mentioned in this forum [post](https://forums.zotero.org/discussion/108835/tool-bar-not-showing-correctly-on-ios)

Improve status bar height initial value

---

Zotero/Scenes/Detail/PDF/Views/AnnotationToolOptionsViewController.swift

Issue reported in forum [post](https://forums.zotero.org/discussion/111633/mobile-drawing-tool-thickness-not-properly-updated/p1)
Will always pass any value change (color and/or size), and not wait for dismissal.
Since there is no cancel action, there is no reason not to simplify as such.

Fix AnnotationToolbarViewController value change

---

Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFAnnotationsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFSidebarViewController.swift

Fixes regression where only annotation comments in the visible cells of the sidebar, are initially cached.
This leads to opening an annotation popover not cached, without an empty comment value.

Fix initial caching of annotation comment not yet visible in the sidebar

---

Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailViewController.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift
Zotero/Scenes/General/NoteEditorCoordinator.swift
Zotero/Scenes/General/ViewModels/NoteEditorActionHandler.swift

Fixes a regression where creating a new note in item details, doesn't use the new note key, so more than one rows, one for each update are shown. This may also leed to a crash if using keyboard validation, like in Japanese IME, that may create an update with the same key and text (reported in app store connect).

Fix note editor callback for new notes in item details

---

Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailViewController.swift

Appstore crash report pointed to a crash in this place, where it would try to unwrap optional and crash because `collectionView` was `nil`. I couldn't reproduce the issue, it was supposed to happen when opening a PDF from a link while another PDF is already opened. But this should at least avoid the crash.

Fixed crash in item detail

---

Zotero/Scenes/Detail/PDF/Views/PDFSearchViewController.swift

From app store screenshot feedback, the bottom document search results on iPhone may be hidden by the keyboard.
While there was already available the `interactive` keyboard dismiss mode, it's not very intuitive for this use case, and a bit cumbersome to accomplish without dismissing the whole screen. Changed it to the `onDrag` mode, and also added dismissal of the keyboard when the search button is tapped.

Improve pdf document search

---

Zotero.xcodeproj/project.pbxproj
Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Extensions/PSPDFKitUI+Extensions.swift
Zotero/Scenes/Detail/PDF/Views/IntraDocumentNavigationButtonsHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFSearchViewController.swift

Reimplements key commands to also display them in the HUD that appears when Command button is pressed in an iPad with an external keyboard.
Currently, if an arrow is pressed, to move to another page, PSPDFKit keyboard shortcuts will appear as such:
Those are suppresed with this PR.
Now by default these commands will appear:
If there is a back action available, those are added as well:
However, if an arrow is pressed, more edit commands will be added, but they are innocuous enough:
Only  `Select All` works to select all the text in the current page.

Improve key commands

---

Zotero/Scenes/Detail/PDF/PDFCoordinator.swift

Fixes regression that draws highlight annotations using the light color when dark mode should be deduced by automatic appearance mode (reported in this forum [post](https://forums.zotero.org/discussion/112571/ios-text-color-changes-instead-of-background-highlight)).

Fix PDF reader interface style initialization

---

ZShare/Controllers/RedirectWebViewHandler.swift
ZShare/ViewModels/ExtensionViewModel.swift

Solves https://github.com/zotero/zotero/pull/3526 for iOS

Fix share PDF download when redirect shows captcha

---

Zotero/Scenes/Detail/PDF/Views/PDFAnnotationsViewController.swift

There is a crash in `PDFAnnotationsViewController` when interface style changes before annotations are loaded.
https://forums.zotero.org/discussion/112601/ios-crash
https://forums.zotero.org/discussion/112583/ios-crash

Fixed annotations data source crash

---

Zotero/Scenes/Detail/PDF/Models/PDFReaderState.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

When annotation is deleted in its popover, it is not dismissed and deselected in the document.
Happens for both document and sidebar popovers.
Fixes https://github.com/zotero/zotero-ios/issues/873

Add PDFReaderState change for selection deletion

---

Zotero/Scenes/Master/Collections/Views/CollectionsViewController.swift

Fixes issue reported in app store connect screenshot [feedback](https://appstoreconnect.apple.com/apps/1513554812/testflight/screenshots/AEnmfF7v9oFojGSaJCmHC04?appPlatform=IOS&sort=-timestamp)

Set collections title line break mode to truncating tail

---

Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift

Fixes regression reported in [1](https://forums.zotero.org/discussion/112840/unable-to-display-document-on-shared-libraries-ios), [2](https://forums.zotero.org/discussion/112810/ios-unable-to-display-document)

Fix creation of download task for shared libraries

---

ZShare/ViewModels/ExtensionViewModel.swift

Syncs item versions as well, when creating download actions for a collections only type of sync. Fixes the edge case mentioned in #882

Fix share extension sync

---

Zotero/Controllers/Controllers.swift
Zotero/Models/Defaults.swift

* Fixes regression in `syncScheduler.inProgress` observer, that  observed `inProgress` initialiazation as well, reseting `Defaults.shared.didPerformFullSyncFix` before it was even used.
* Adds `Default.shared.performFullSyncGuard` & `Defaults.currentPerformFullSyncGuard` that are used to reset `Defaults.shared.didPerformFullSyncFix` to `false` when neeeded. Increment `Defaults.currentPerformFullSyncGuard` by `1`, to trigger a full sync in existing installations on an upcoming release. New installations don't trigger a full sync.

Improve full sync fix trigger

---

Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Controllers/AttachmentCreator.swift
Zotero/Models/Attachment.swift
Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift
Zotero/Scenes/Master/Settings/Sync/ViewModels/SyncSettingsActionHandler.swift

* Fixes WebDAV authentication regression. It happened because of a side-effect when dismissing the Account screen, that didn't affect the previous solution. Upon dismissal, if a text field still had first responder, it caused the WebDAV verification to be reset. However (a) the authentication header was set by alamofire and (b) the WebDAV server was checked if needed before each download, restoring the verification. New solution, stored also the WebDAV authentication header in the `ZoteroApiClient` instance, so these were lost upon Account screen dismissal, which are used directly when creating a `URLRequest`.
* Updates `Attachment` compressed status for local files, when these become ready. This may change in such a scenario:
* user installs app and all items are created via Zotero API, …

Fix WebDAV authentication and opening attachments

---

Zotero/Scenes/Detail/PDF/Views/IntraDocumentNavigationButtonsHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Fixes https://forums.zotero.org/discussion/113134/back-button-on-ipad-disappeared

Fixed intra-pdf back button visibility

---

Zotero/Controllers/Controllers.swift

* Stores a value to `Defaults.shared.didPerformFullSyncFix` even when one is not triggered, so otherwise it is always assumed a new installation.
* Also improves related logging.

Improve full sync fix

---

ZShare/View Controllers/ShareViewController.swift
ZShare/ViewModels/ExtensionViewModel.swift
Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/Database/Requests/DeleteFailedItemsDbRequest.swift
Zotero/Controllers/Sync/SyncActions/SubmitUpdateSyncAction.swift
Zotero/Controllers/Sync/SyncController.swift
Zotero/Models/Sync/SyncErrors.swift

Fixes #893, also in #891 I missed a case, where metadata editing is enabled, but file editing is disabled, in that case, we'd get "unknown" error in share extension too. This time we show proper error all the time. Share extension also cleans up after itself if there is an error, so we don't have any items which shouldn't exist.

Improved share extension error handling

---

Zotero/Scenes/Detail/PDF/Views/AnnotationToolbarHandler.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationToolbarViewController.swift
Zotero/Scenes/Detail/PDF/Views/DashedView.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Generalizes the architecture of the annotation toolbar handler, to allow for also handling a future open documents tab bar.
There are several (pre-existing) edge cases, when a phone device is rotated to landscape, which could be improved with some more streamlining, especially regarding the annotation toolbar view controller layout. I guess though, that those edge cases might not be ones users are partial to, otherwise we might have gotten relevant feedback.

Improve annotation toolbar handler

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Extensions/Localizable.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Master/MasterCoordinator.swift
Zotero/Scenes/Master/Settings/SettingsCoordinator.swift

Handles the edge case where an attachment download task will finish with status code 401, but it is masked by another error message. User case in this forum [comment](https://forums.zotero.org/discussion/comment/461352/#Comment_461352).
We may need to handle more specific status codes explicitly.

Improve URLSession HTTP download response handling

---

Zotero.xcodeproj/project.pbxproj
Zotero.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

@dstillman @michalrentka the latest release of PSDFKit (13.5.0) improves the highlight annotation gap issue (#880) , but doesn't resolve it completely. It still keeps some gaps between sentences. Should we go ahead and merge it, or stick with 13.3.1 until it's further resolved? (I've already replied in the original ticket we had with PSPDFKit)
Highlight 13.3.1:
Selection 13.3.1:
Highlight 13.5.0:
Selection 13.5.0:

Fix PDF document gaps for selection and highlight annotations

---

Zotero/Controllers/CommentIconDrawingController.swift

Fixes issue mentioned in forum [post](https://forums.zotero.org/discussion/115061/ios-double-area-annotation-comment-icons)

Fix annotation comment icon drawing

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/WebDAV/WebDavController.swift
Zotero/Extensions/Localizable.swift
Zotero/Scenes/General/Views/SyncToolbarController.swift
Zotero/Scenes/Master/Settings/Sync/Views/SyncSettingsView.swift

Add proper error message for ATS

---

Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Controllers/Controllers.swift

If user signs out and signs in again, without terminating the app, their downloads are still handled by the leaked delegate, and cannot be finished.

Fix AttachmentDownloader URLSession memory leak

---

Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/AnnotationPreviewController.swift
Zotero/Controllers/CommentIconDrawingController.swift
Zotero/Scenes/Detail/PDF/Models/AnnotationManager.swift
Zotero/Scenes/Detail/PDF/Models/PDFReaderState.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/SquareAnnotationView.swift

Draws the comment icon, if needed, for a selected square annotation, as PSPDFKit ignores the overridden drawing in the `SquareAnnotation` class. The drawing is not exact, if you zoom it's obvious. On the other hand, even the selection itself moves the annotation square a little bit 🤷‍♂️

Improve selected square annotation drawing

---

Zotero/Controllers/AnnotationConverter.swift
Zotero/Controllers/AnnotationPreviewBoundingBoxCalculator.swift
Zotero/Scenes/Detail/PDF/Models/PDFAnnotation.swift
Zotero/Scenes/Detail/PDF/Models/PDFDatabaseAnnotation.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

I cleaned up loading of annotations for pdf viewer so that we don't go through all annotations multiple times, which leads to some small-ish performance improvements. If we want to improve loading further we'd probably have to load annotations in batches instead of all at once.

Performance improvements in PDF Viewer

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

By default, as mentioned in this forum [post](https://forums.zotero.org/discussion/114937/ios-keyboard-navigation), keyboard navigation ignores that a page is zoomed in, and moves directly to the previous/next page, in the same zoom level. Additional key commands, allow to alternatively move to the previous/next viewport.

Add in PDF reader previous/next viewport key commands

---

Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

1.) Fixes a bug where double tapping on the Apple Pencil could activate annotation mode without any UI change, mentioned here:
https://forums.zotero.org/discussion/105598/bug-ipad-douple-tapping-apple-pencil-activates-annotation-tools-outside-of-annotation-mode
https://forums.zotero.org/discussion/115677/ios-apple-pencil-double-tap-and-annotation-panel
2.) Adds more annotation tools and functionality to the Apple Pencil "Switch Between Current Tool and Last Used" double-tap mode. Currently, this mode ignores the eraser and also has no way to switch tools *off*. I've found that other PDF readers interpret this mode to include "no tool" as a switchable state (PDF Expert) so that users can double tap to activate and deactivate tools. Other PDF readers have a designated "hand" tool …

Fix Apple Pencil double-tap bug and add more tool switching functionality

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Extensions/PSPDFKitUI+Extensions.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

* Moves arrow key command logic to PSPDFKitUI extensions
* Properly shows all arrow key commands in shortcuts HUD.
* Improves simple arrow key commands (i.e. w/o modifiers) to move to previous/next page middle.

Improve PDF reader arrow key commands

---

Zotero/Controllers/AttachmentCreator.swift
Zotero/Extensions/MD5+Url.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

There is a number of reported Hangs for version 1.0.39, when MD5 hashes are computed. These are re-computed every time a document appears as downloaded in a collection, or it is opened. Adding a simple session memory cache, can speed subsequent uses if the file has not been modified.

Cache file MD5 and modification date by URL for app session

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/AttachmentFileCleanupController.swift
Zotero/Extensions/Localizable.swift
Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift
Zotero/Scenes/Detail/Items/Models/ItemAction.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsToolbarController.swift
Zotero/Scenes/Detail/Items/Views/ItemsTableViewHandler.swift
Zotero/Scenes/Master/Collections/Models/CollectionsAction.swift
Zotero/Scenes/Master/Collections/ViewModels/CollectionsActionHandler.swift
Zotero/Scenes/Master/Collections/Views/ExpandableCollectionsCollectionViewHandler.swift
Zotero/Scenes/Master/MasterCoordinator.swift

* Adds `Remove Downloads` action in collection context menu, when the collection has items. Similar to `Download Attachments` action, it doesn't explicitely check if there are any attachments already downloaded, it just checks for collection items count. This action is placed 2nd in the menu, after `Download Attachments`. For `Trash` it is placed 1st, as non-destructive.
* Adds `Remove downloads for selected items` action in items toolbar. To differentiate from `Move selected items to trash` the icon  `arrow.down.circle.dotted` is used.
Perhaps we should consider using the same icon, either a system or a custom one, for all actions that remove downloads.
Additionally, since we allow to remove downloads for selected items, maybe we should also allow to download attachments for selected …

Add collection remove downloads action

---

Zotero/Controllers/PlaceholderTextViewDelegate.swift
Zotero/Scenes/Detail/PDF/Models/AnnotationViewLayout.swift
Zotero/Scenes/Detail/PDF/Models/PDFReaderAction.swift
Zotero/Scenes/Detail/PDF/Models/PDFReaderState.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationView.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewHighlightContent.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewTextView.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationCell.swift
Zotero/Scenes/Detail/PDF/Views/PDFAnnotationsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Coverts annotation text for highlight and underline annotations to attributed text, for proper read-only presentation in annotations sidebar. Caches attributed text in PDF reader state. Updates cache whenever annotation text changes.
A separate issue will be opened to add formatting for annotation edit as well, similar to annotation comment edit.

Show formatted text in annotations sidebar

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

Transforms highlight annotation that are added by a user in the device, if there are overlapping line rects, by trimming equidistantly.
Closes #984

Add highlight annotation transformation for overlapping lines

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

When user resizes a free text annotation, potential font size change is not communicated in the notification received by PSPDFKit (using `notification.userInfo?[PSPDFAnnotationChangedNotificationKeyPathKey]`), and therefore is not synced. Updating `fontSize` whenever a free text annotation has a `boundingBox` change, even if font size didn't change, fixes this on our side. 
I'll also report this to PSPDFKit, as it seems an omission on their side.

Add free text annotation font size update when resizing

---

Zotero/Models/Database/Database.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

Closes https://github.com/zotero/zotero-ios/issues/1002

Fix annotation color in dark appearance

---

Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift

Standalone items use their key also as parent key, affecting e.g. PDF share menu.
Mentioned in forum [comment](https://forums.zotero.org/discussion/comment/473613/#Comment_473613)

Set correct parent key for standalone item accessory

---

Zotero/Models/KeyboardData.swift

Reported in this forum [post](https://forums.zotero.org/discussion/116618/bug-annotating-in-ipad-can-t-see-the-text-box)
For floating keyboards the computation is not valid, and would create a wrong content inset for the sidebar table view, after the keyboard has hidden once.

Improve keyboard visible height calculation

---

Zotero/Scenes/Master/Collections/Views/CollectionsViewController.swift
Zotero/Scenes/Master/Collections/Views/ExpandableCollectionsCollectionViewHandler.swift
Zotero/Scenes/Master/MasterCoordinator.swift

Fixes issue mentioned in https://forums.zotero.org/discussion/104723/download-all-files-in-ios-app

Fix collection context menu when collection size is not shown

---

Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Controllers/WebDAV/WebDavSessionStorage.swift

Fixes loss of "verification" for WebDAV, as reported in https://forums.zotero.org/discussion/118829/ios-webdav-timeouts

Handle URLSession WebDAV auth challenge

---

Zotero/Scenes/Detail/ItemDetail/Models/ItemDetailAction.swift
Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailCollectionViewHandler.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailNoteCell.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailNoteContentView.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailViewController.swift

Improves UI performance for item details. When there is a large number of sizable notes, e.g. ones created from annotations, scrolling becomes sluggish, and opening attachments from the details view causes the app to hang as the loading of the file is very slow.

Improve item details UI performance

---

Zotero/Scenes/Detail/Annotation Popover/AnnotationPopoverCoordinator.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

* Allows quicker annotation popover selection, as before closing e.g. a highlight annotation and selecting immediatelly another, is ignored.
* Fixes deselection of annotations, when there are more than one visible page views.

Improve PDF reader annotation selection/deselection

---

Zotero/Controllers/AnnotationPreviewController.swift
Zotero/Controllers/PDFThumbnailController.swift

Closes #1023 
This could be due to a large number of annotation previews. `pngData` may be called with a larger frequency than this  of memory release, resulting in this type of crash, regardless that a background queue is used. If so, an auto release pool may be enough to force memory purging.

Auto release computed PNG data after caching

---

Zotero.xcodeproj/project.pbxproj
Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/Controllers.swift
Zotero/Controllers/IdleTimerController.swift
Zotero/EventObservableWindow.swift
Zotero/Extensions/Localizable.swift
Zotero/SceneDelegate.swift
Zotero/Scenes/Detail/PDF/Models/PDFSettings.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/General/Models/ReaderSettingsAction.swift
Zotero/Scenes/General/Models/ReaderSettingsState.swift
Zotero/Scenes/General/ViewModels/ReaderSettingsActionHandler.swift
Zotero/Scenes/General/Views/ReaderSettingsViewController.swift

Implemented custom idle timer logic

---

Zotero/Scenes/Detail/Items/Views/BaseItemsViewController.swift

Fixes issue mention in this forum [post](https://forums.zotero.org/discussion/119807/ios-search-field-overlaps-with-item-list)

Fix items search bar placement iOS 18 bug

---

Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

Fixes regression introduced in #1024

Fix annotation popover regression

---

Zotero.xcodeproj/project.pbxproj
Zotero/Scenes/Detail/PDF/Views/FreeTextAnnotationView.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

Should improve sync between different clients, for those text annotations that are created in iOS.

Adjust free text annotation size on editing end

---

Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailCollectionViewHandler.swift
Zotero/Scenes/Detail/Lookup/Views/LookupViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFAnnotationsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFThumbnailsViewController.swift
Zotero/Scenes/General/Views/CollectionsPickerViewController.swift
Zotero/Scenes/Master/Collections/Views/CollectionsSearchViewController.swift
Zotero/Scenes/Master/Collections/Views/ExpandableCollectionsCollectionViewHandler.swift

Moved diffable data sources to background queue

---

Zotero/Models/API/ItemResponse.swift

From crash reported in this forum [post](https://forums.zotero.org/discussion/120455/ios-crash-report-528986590)
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSJSONSerialization dataWithJSONObject:options:error:]: Invalid top-level type in JSON write'
```

Fix item response position fields parsing

---

Zotero/Scenes/Detail/PDF/Models/PDFDatabaseAnnotation.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

Fixes issue reported in forum [post](https://forums.zotero.org/discussion/118984/autolocking-annotations-on-ipad)
When an annotation is transformed, e.g. due to overlapping rects or rects that need to be split, the new annotations are added using `document.add`. If these annotations have an empty string for the `user` field, the field is converted to `nil`. This will cause the PSPDFKIT annotation to be added in the database with `createdBy = nil`, until the next sync happens, that will assign the proper user.
Guarantying a non-empty `user` field, alleviates the issue. Alternatively, we can consider adding the `username` or event better the `userId`, in the annotation `customData`, and not rely at all to `user`.

Fix transformed annotation user

---

Zotero/Scenes/Detail/PDF/Views/PDFAnnotationsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFThumbnailsViewController.swift
Zotero/Scenes/Master/Collections/Views/ExpandableCollectionsCollectionViewHandler.swift

Should fix issue reported in [submitted crash](https://forums.zotero.org/discussion/120874/ios-crash-report-600618183)

Fix PDFAnnotationsViewController edge case bug

---

Zotero/Scenes/Master/Collections/Views/ExpandableCollectionsCollectionViewHandler.swift

Potential fix for crash reported via apple reports and forum posts. Not reproduced yet.

Fix ExpandableCollectionsCollectionViewHandler data source crash

---

Zotero.xcodeproj/project.pbxproj
Zotero/AppDelegate.swift
Zotero/Models/Defaults.swift

Added custom chinese font

---

.gitignore
Zotero.xcodeproj/project.pbxproj
ci_scripts/ci_post_clone.sh

Moves `fonts` directory to `bundled`, as it streamlines more the project structure and fixes a github action issue.

Move fonts directory to bundled

---

Zotero/Controllers/Database/Requests/CancelParentCreationDbRequest.swift
Zotero/Controllers/Database/Requests/CreateItemFromDetailDbRequest.swift
Zotero/Controllers/Database/Requests/MoveItemsToParentDbRequest.swift
Zotero/Controllers/Database/Requests/RemoveItemFromParentDbRequest.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/ItemDetail/Models/ItemDetailState.swift
Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift

Modifies these item actions to be in sync with the desktop implementations:
* Move item to an existing parent, by drag and drop.
* Move item to manually created parent. This action can be canceled. 
* Remove item atttachment from its parent, back to a standalone item.

Improve attachment move to/from parent actions

---

Zotero/Controllers/Database/Requests/CreatePDFAnnotationsDbRequest.swift

Assign empty value in case field is unknown when creating annotations

---

Zotero/Info.plist

Allow Insecure HTTP for Reserved IP addresses (not covered by NSAllowsLocalNetworking)
When using private networking software, this option is required to allow intranet HTTP traffic.

Allow Insecure HTTP for Reserved IP addresses (not covered by NSAllowsLocalNetworking)

---

Zotero/Extensions/PSPDFKit+Extensions.swift
Zotero/Scenes/Detail/PDF/Views/IntraDocumentNavigationButtonsHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Improve intra document navigation

---

Zotero.xcodeproj/project.pbxproj
Zotero/Scenes/Detail/PDF/Models/BackForwardActionList.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

It avoids having the navigation forward action list reset when the user scrolls manually to another page.

Improve intra document navigation when user scrolls to a different page

---

ZShare/View Controllers/ShareViewController.swift

Since tags are ignored when creating the database item for a shared file without a parent, the tags picker is shown only when needed, so that there are no false user expections.

Show share extension tags picker only for translated items

---

ZShare/Controllers/TranslationWebViewHandler.swift
Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/Citation/CitationController.swift
Zotero/Controllers/IdentifierLookupController.swift
Zotero/Controllers/Web View Handling/CitationWebViewHandler.swift
Zotero/Controllers/Web View Handling/LookupWebViewHandler.swift
Zotero/Controllers/Web View Handling/WebViewHandler.swift
Zotero/Scenes/Detail/CitationBibliographyExport/CitationBibliographyExportCoordinator.swift
Zotero/Scenes/Detail/CitationBibliographyExport/Models/CitationBibliographyExportState.swift
Zotero/Scenes/Detail/CitationBibliographyExport/ViewModels/CitationBibliographyExportActionHandler.swift
Zotero/Scenes/Detail/CitationBibliographyExport/Views/CitationBibliographyExportView.swift
Zotero/Scenes/Detail/CopyBibliography/Models/CopyBibliographyAction.swift
Zotero/Scenes/Detail/CopyBibliography/Models/CopyBibliographyState.swift
Zotero/Scenes/Detail/CopyBibliography/ViewModels/CopyBibliographyActionHandler.swift
Zotero/Scenes/Detail/CopyBibliography/Views/CopyBibliographyViewController.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift
Zotero/Scenes/Detail/SingleCitation/Models/SingleCitationAction.swift
Zotero/Scenes/Detail/SingleCitation/Models/SingleCitationState.swift
Zotero/Scenes/Detail/SingleCitation/ViewModels/SingleCitationActionHandler.swift
Zotero/Scenes/Detail/SingleCitation/Views/SingleCitationViewController.swift
Zotero/Scenes/Master/Libraries/Views/LibrariesViewController.swift
Zotero/Scenes/Master/MasterCoordinator.swift

Refactors citation controller to two a citation web view handler part and a citation controller part that allows multiple citation sessions, even without an explicitly provided web view, useful if preview is not desired. These changes will be used in drag-and-drop of items to generate a bibliography text representation rather than using the item key.

Refactor citation controller

---

Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/API/Alamofire+RxSwift.swift
Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Models/RetryDelay.swift

Fixes handling of attachment download response when status code is `429` (Too Many Requests).
From forum [post](https://forums.zotero.org/discussion/124137/ios-debug-log-d1883589021/)
Check also #1116

Handle status response 429 as an error for download tasks

---

Zotero/Controllers/TextConverter.swift

Sanitize markedUpString from PDF documents before use

---

Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift
Zotero/Scenes/Detail/Trash/ViewModels/TrashActionHandler.swift

Fixes an issue where downloading not the default attachment in item details, and then going back, would show the in the items screen the default attachment as downloaded, which would result in an error when attempting to open. Issue didn't appear if the specific collections items reloaded, e.g. by changing collections, only when going directly from item details to its collection items screen.

Fix item default attachment

---

Zotero/Controllers/Architecture/Coordinator.swift
Zotero/Scenes/Main/Views/MainViewController.swift

Fixes edge case where hidden detail coordinator change would cause an unintended deinititalization of the presented view controller's coordinator.

Improve detail coordinator change

---

ZShare/ViewModels/ExtensionViewModel.swift

Fixes shared remote file URL recognition.

Recognize shared remote file if PDF

---

Zotero/Scenes/Main/Views/MainViewController.swift
Zotero/Scenes/Master/Collections/Views/CollectionsViewController.swift

In iOS 26 setting the `MainViewController`'s `viewControllers` directly doesn't update its 'children` at once (possibly an iOS 26 bug), resulting in faulty logic in `CollectionsViewController` `viewDidLoad`, that shows detail view controller blank. This is fixed by assuming that lack of a `splitViewController reference` means a split state.

Fix SplitControllerDelegate for iOS 26

---

Zotero/Scenes/Master/Collections/ViewModels/CollectionsActionHandler.swift

Potential fix for issue reported in this forum [post](https://forums.zotero.org/discussion/125361/ios-crash-report-666393121/).
The crash with the error `swift_unknownObjectUnownedLoadStrong` when accessing`dbStorage` in the nested fuction `updateTrashCount`. Both calls of this are in `Results<RItem>` observation blocks. Converting the struct to class allows to also weakly capture `self` and also pass explicitely to nested functions after guarding that it is valid.
If we still get similar crashes though, perhaps due to internal iOS changes that cause these edge cases, we should consider refactoring `BackgroundDbProcessingActionHandler` `dbStorage` to `DbStorage?` so that it can be `weak` when implementing the protocol.

Fix collections action handler crash

---

Zotero/Controllers/Architecture/Coordinator.swift
Zotero/Scenes/Detail/CitationBibliographyExport/CitationBibliographyExportCoordinator.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/HTML:EPUB/Views/HtmlEpubReaderViewController.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailCollectionViewHandler.swift
Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailViewController.swift
Zotero/Scenes/Detail/Items/Views/ItemsTableViewHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationToolbarViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Detail/ReaderCoordinator.swift
Zotero/Scenes/Detail/Trash/Views/TrashViewController.swift
Zotero/Scenes/Master/Settings/SettingsCoordinator.swift

Simplifies popover logic according to latest iOS versions (16+):
- Prefers `popoverPresentationController` `sourceItem`. (Still uses `sourceView` & `sourceRect` where needed).
- Uses just `modalPresentationStyle` `.popover` where applicable, since it implies `formSheet` for horizontally or vertically compact environments.

Improve popover source item logic

---

ZShare/View Controllers/ShareViewController.swift
ZShare/ViewModels/ExtensionViewModel.swift
Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/Web View Handling/WebViewHandler.swift

* Logs and reports as failure provisional navigation errors.
* Uses specific fatal error when an app/site requires a browser explicitly.
* Improves web view handler custom user agent to potentially overcome such app/sites requirement.

Improve share extension web view handler

---

Zotero/Scenes/Detail/PDF/Views/AnnotationCell.swift
Zotero/Scenes/Detail/PDF/Views/PDFAnnotationsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFSidebarViewController.swift

Fixes potential crash reported in https://forums.zotero.org/discussion/126827/ios-crash-report-1397306611
* Fixes `AnnotationCell` memory leak, due to `disposeBag` not being disposed when an instance was deinitialized.
* Improves memory management of `ViewModel<PDFReaderActionHandler>` instances.

Fix PDF reader memory leak

---

Zotero/Models/AnnotationsConfig.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Fixes hang issue mentioned in https://forums.zotero.org/discussion/126895/text-annotation-and-selection-issues-on-ipad
When loading a document with numerous link annotations, (8000+ in this case), setting all to locked will mark annotations as dirty. Upon clicking a link action for the first time, the document will try to save dirty annotations, causing a flurry of notificaitons and saves that use barriers. It seems that link annotations can be ignored, as they don't seem to be editable. 
Made more explicit with a relevant document builder configuration.

Improve PDF document load

---

Zotero/Controllers/Database/Requests/ReadItemsDbRequest.swift
Zotero/Models/Predicates.swift
Zotero/Scenes/Master/Collections/Models/CollectionsState.swift
Zotero/Scenes/Master/Collections/ViewModels/CollectionsActionHandler.swift

Potential fix for crash reported in https://forums.zotero.org/discussion/127210/ios-crash-report-956913126
Also, adds another item changes observer, that will update count when items are deleted, as this action doesn't bring any change to the collection keypaths already observed.

Improve item count observation
