zotero/zotero-ios

Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/ItemDetail/Models/ItemDetailError.swift
Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift

fix cancel create item manually

---

Zotero/Controllers/Database/Requests/EditItemFromDetailDbRequest.swift

fix error that was preventing changing author type

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Call function to store annotation previews

---

Zotero.xcodeproj/project.pbxproj
Zotero.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ZoteroTests/CollectionResponseSpec.swift
ZoteroTests/CreatorSummaryFormatterSpec.swift
ZoteroTests/DateParserSpec.swift
ZoteroTests/ItemResponseSpec.swift
ZoteroTests/ItemTitleFormatterSpec.swift
ZoteroTests/ReadUpdatedItemUpdateParametersSpec.swift
ZoteroTests/SearchResponseSpec.swift
ZoteroTests/StorageSettingsActionHandlerSpec.swift
ZoteroTests/SyncActionsSpec.swift
ZoteroTests/SyncControllerSpec.swift
ZoteroTests/TranslatorsControllerSpec.swift
ZoteroTests/WebDavControllerSpec.swift

* Updates test dependencies Quick & Nimble to latest versions
* Migrates existing tests
* Refactors the least complex ones, to improve clarity

Update test dependencies Quick & Nimble

---

Zotero/Controllers/AnnotationConverter.swift
Zotero/Controllers/Database/Requests/CreateAnnotationsDbRequest.swift
Zotero/Models/API/ItemResponse.swift
Zotero/Models/FieldKeys.swift
Zotero/Scenes/Detail/PDF/Models/PDFReaderAction.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

Also fixed annotation creation bug, closes #706

Implemented new PSPDFKit menu API

---

Zotero/Extensions/NSUserActivity+Activities.swift
Zotero/Scenes/AppCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Main/Views/MainViewController.swift
Zotero/Scenes/Master/MasterTopCoordinator.swift

Revert "Show proper hierarchy when there is restored state"

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

Update annotation in document when comment changes

---

Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFSearchViewController.swift

I also added cmd+f to items list and you can press Esc to close the search popup. Closes #699.

Implemented cmd+f command to pdf reader and items list

---

Zotero/Models/Predicates.swift

This is hopefully a temporary fix for a Realm issue.

Fixed crash when searching for item keys

---

Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

closes https://github.com/zotero/zotero-ios/issues/743

Deselect text after highlight creation

---

Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift

Also replaced highlight button with a custom one

Fixed missing highlight button in some PDFs

---

Zotero/Controllers/IdleTimerController.swift
Zotero/Controllers/Sync/SyncScheduler.swift

Fixed SyncScheduler progress reporting

---

Zotero/Scenes/Detail/Items/Views/ItemsTableViewHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift

Revert back to opening metadata on cell tap

---

Zotero/Controllers/Sync/SyncController.swift
ZoteroTests/SyncControllerSpec.swift

If during batch syncing when downloading multiple items from server to database some API request returns 500 (or other non-fatal status code), listed items are not downloaded, but they were not marked for sync, so they would just be skipped and forgotten. In case of errors returned by `SyncBatchProcessor` mark keys for resync so that they are re-downloaded later.
Fixes #759

Fixed some items not being synced due to errors

---

ci_scripts/ci_pre_xcodebuild.sh

Fixed xcode pre-build script to accomodate new pdf-key format

---

Zotero/Controllers/Sync/SyncController.swift

If the user had only submissions/uploads queued and reached quota limit, sync controller wouldn't check for remote changes on 413 response.
Fixes #775

Check for remote changes when quota limit is reached

---

Zotero.xcodeproj/project.pbxproj
Zotero.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Zotero/Controllers/Database/Requests/MoveItemsToParentDbRequest.swift
Zotero/Controllers/Database/Requests/RemoveItemFromParentDbRequest.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift

Fixed item list icon not updated when main attachment is added/removed

---

Zotero/Controllers/API/Requests/WebDavCheckRequest.swift

Enable 204 response for options webdav request

---

Zotero/Scenes/Detail/PDF/Models/PDFReaderState.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/AnnotationsViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Possible fix for #798, caused by memory leak in PDF reader.

Fixed memory leak in PDF viewer

---

Zotero/Scenes/Detail/PDF/PDFCoordinator.swift

Fixes https://github.com/zotero/zotero-ios/issues/798

Fix share annotation image deferred menu memory leak

---

Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFSearchViewController.swift

* Maintains current search when results window is dismissed
* Highlights all search results until search bar text changes or is cleared
* Adds extra highlight for selected search result
Improvements mentioned by users in [forum post](https://forums.zotero.org/discussion/109222/ios-pdf-reader-improvement-request)

Improve PDF search

---

Zotero.xcodeproj/project.pbxproj
Zotero/AppDelegate.swift
Zotero/Controllers/Database/Requests/CleanupUnusedTags.swift
Zotero/Controllers/Database/Requests/CreateNoteDbRequest.swift
Zotero/Controllers/Database/Requests/EditNoteDbRequest.swift
Zotero/Controllers/Database/Requests/EditTagsForItemDbRequest.swift
Zotero/Controllers/Database/Requests/ReadEmojiTagsDbRequest.swift
Zotero/Controllers/Database/Requests/ReadFilteredTagsDbRequest.swift
Zotero/Controllers/Database/Requests/StoreItemsDbResponseRequest.swift
Zotero/Controllers/Database/Requests/StoreSettingsDbRequest.swift
Zotero/Controllers/EmojiExtractor.swift
Zotero/Models/Database/Database.swift
Zotero/Models/Database/RTag.swift
Zotero/Models/Predicates.swift
Zotero/Models/Tag.swift
Zotero/Scenes/Detail/Items/Models/ItemCellModel.swift
Zotero/Scenes/Detail/Items/Views/ItemCell.swift
Zotero/Scenes/Detail/Items/Views/ItemCell.xib
Zotero/Scenes/Detail/Items/Views/TagCirclesView.swift
Zotero/Scenes/Detail/Items/Views/TagEmojiCirclesView.swift
Zotero/Scenes/General/ViewModels/TagPickerActionHandler.swift
Zotero/Scenes/Master/TagFiltering/ViewModels/TagFilterActionHandler.swift
ZoteroTests/EmojiExtractorSpec.swift
ZoteroTests/SyncControllerSpec.swift

Emojis in tags improvements

---

Zotero/Scenes/Master/TagFiltering/Views/TagFilterCell.swift

Fixed font in tag filter controller, fixes #732

Tag filter font fix

---

Zotero/Scenes/Detail/PDF/Views/AnnotationToolbarHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Improves code related to `AnnotationToolbarHandler`

Improve code

---

Zotero/Scenes/Detail/PDF/Models/PDFDocumentAnnotation.swift

Lock all annotations loaded from document

Fixed loading annotations from document

---

Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailCollectionViewHandler.swift

Simple fix for existing crash. This way users will also hopefully report an UI issue and we can have them log more data to figure out what's wrong. If we just crash we don't get anything else.
Related issues:
https://forums.zotero.org/discussion/111683/ios-crash-log-sent
https://forums.zotero.org/discussion/109208/ios-app-crashes-when-clicking-on-information-button-of-an-entry

Don't crash on identical tags in item detail

---

Zotero.xcodeproj/project.pbxproj
Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Scenes/Detail/PDF/Views/IntraDocumentNavigationButtonsHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Added intra-pdf link navigation to pdf reader

---

Zotero/Controllers/API/Alamofire+RxSwift.swift

Fixed retrying of API requests when WebDAV is full

---

Zotero/Scenes/Detail/PDF/Views/AnnotationToolbarHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

* Improves status bar height computation.
* Improves interface visibility change animation.
* Fixes annotation popover vertical placement for some toolbar positions and interface visibility combinations.

Improve annotation toolbar logic

---

Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Fixed locked up state when restoring locked document

---

Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/Database/Requests/CountObjectsDbRequest.swift
Zotero/Controllers/Database/Requests/PerformDeletionsDbRequest.swift
Zotero/Controllers/Sync/SyncActions/PerformDeletionsSyncAction.swift
Zotero/Controllers/Sync/SyncController.swift

Fixes https://forums.zotero.org/discussion/112721/ios-crash

Fixed crash when account has too many deletions

---

Zotero/Controllers/Web View Handling/WebViewHandler.swift

Updated custom user agent to include default iOS user agent

---

Zotero.xcodeproj/project.pbxproj
Zotero/PrivacyInfo.xcprivacy

Resources:
* https://mastodon.social/@chockenberry/112095474802156488
* https://developer.apple.com/documentation/bundleresources/privacy_manifest_files#4284009
* https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Add privacy manifest

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Scenes/Detail/PDF/Models/PDFSettings.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/General/Models/ReaderSettingsAction.swift
Zotero/Scenes/General/Models/ReaderSettingsState.swift
Zotero/Scenes/General/ViewModels/ReaderSettingsActionHandler.swift
Zotero/Scenes/General/Views/ReaderSettingsViewController.swift

Page spreads implemented

---

Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Controllers/Attachment Downloader/RemoteAttachmentDownloadOperation.swift

Fix WebDAV not found error handling

---

Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift

Check https://github.com/zotero/zotero-ios/issues/906

Delete downloaded attachment on error

---

ZShare/ViewModels/ExtensionViewModel.swift

Fix save of local file when over quota limit

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Scenes/AppCoordinator.swift

Re-added copy debug id button

---

Zotero/Extensions/NSUserActivity+Activities.swift
Zotero/Extensions/UIViewController+Extensions.swift
Zotero/SceneDelegate.swift
Zotero/Scenes/Detail/PDF/Models/PDFReaderState.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Main/Views/MainViewController.swift

Suggested in this forum [post](https://forums.zotero.org/discussion/comment/461420/#Comment_461420)

Set scene title

---

Zotero/Controllers/AnnotationPreviewController.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift

Fixed regression in #924. It didn't render annotations.

Regression fixed

---

Zotero/Extensions/PSPDFKitUI+Extensions.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Suggestion from forum [post](https://forums.zotero.org/discussion/114377/ipados-copy-from-pdfs-with-shortcut-cmd-c/p1)

Add copy text key command in PDF reader

---

Zotero/Controllers/AnnotationPreviewController.swift
Zotero/Controllers/PDFThumbnailController.swift
Zotero/Scenes/Detail/PDF/Models/PDFThumbnailsAction.swift
Zotero/Scenes/Detail/PDF/Models/PDFThumbnailsState.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFThumbnailsActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFSidebarViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFThumbnailsViewController.swift

PDF reader thumbnails fix

---

Zotero/Controllers/Database/Requests/SyncVersionsDbRequest.swift
Zotero/Scenes/Master/Libraries/Views/LibrariesViewController.swift

Fixed repeated delete group prompt

---

Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift

Fixed crash when updating items list

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/PDF/Models/PDFReaderState.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Fixed crash of remotely changed and updated document

---

Zotero/Controllers/Database/Requests/CreatePDFAnnotationsDbRequest.swift

When an annotation is deleted, if the action is undone, then the `annotation.rects` will be appended again to the `item.rects`. If you exit the document, and open it again, these rects will be draw with multiply blend mode, resulting in a darker annotation color.
It seems that returning after toggling the `item.deleted` property should be enough for this type of restoration.

Fix restoration of deleted annotation

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFThumbnailsActionHandler.swift

Fix crashing when last visible page was the last one in document and it has been deleted

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

Debouncing all annotation changes, creates a race issue when merging ink annotations. As merging also removes annotations, the removal will cause a database update, that will disable notifications temporarily. The debounce delay may cause the annotation change notification to not be observed, if it falls in the disabled period. Debouncing after the notification is received, resolves the issue.
As a further improvement, the debouncing happens only for the offending annotation type and change.
Closes #921

Debounce free text annotation rotation by key

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

* Refactors code.
* Fixes bug when annotation is split.
* Pops undo stack and records proper undo command when an added annotation has been transformed.

Improve PDF reader action handler

---

Zotero.xcodeproj/project.pbxproj
Zotero/Assets/en.lproj/InfoPlist.strings
Zotero/Extensions/NSUserActivity+Activities.swift
Zotero/Info.plist
Zotero/SceneDelegate.swift
Zotero/Scenes/AppCoordinator.swift
swiftgen.yml

Adds "Reset open item" static application shortcut, that can be used in the edge case where the app restores an item that immediately crashes. It can be selected by long tapping on the app icon.

Add reset open item application shortcut

---

Zotero/Scenes/Detail/DetailCoordinator.swift

Fixed url detection in show web function

---

ZShare/Controllers/TranslationWebViewHandler.swift
Zotero/Controllers/Web View Handling/WebViewHandler.swift

Fixed referer header in share extension

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Extensions/Localizable.swift
Zotero/Models/Defaults.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/General/NoteEditorCoordinator.swift
Zotero/Scenes/Master/Settings/General/Models/GeneralSettingsAction.swift
Zotero/Scenes/Master/Settings/General/Models/GeneralSettingsState.swift
Zotero/Scenes/Master/Settings/General/ViewModels/GeneralSettingsViewModel.swift
Zotero/Scenes/Master/Settings/General/Views/GeneralSettingsView.swift

Added option to open links in external browser

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

There seems to be an edge case where removing a transformed annotation, throws undocumented PSPDFKit error `The removed annotation does not belong to the current document`, causing a crash. (Reported in forum [post](https://forums.zotero.org/discussion/115287/ios-crash-report-1677056178) and other submitted crashes.) Check in PR helps avoid that.

Improve transformed annotation removal

---

Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewHeader.swift
Zotero/Scenes/Detail/PDF/Views/Annotation View/AnnotationViewImageContent.swift

Fixed autolayout warnings in PDF reader sidebar

Fixed autolayout issues in PDF reader

---

Zotero/Scenes/Detail/DetailCoordinator.swift

Fixed edge case found thanks to https://forums.zotero.org/discussion/comment/467280

Fixed AFError/AFResponseError check from AttachmentDownloader

---

Zotero/Scenes/Detail/Annotation Popover/Views/AnnotationPopoverViewController.swift

Fixed a crash from our internal crash logs

Fixed unwrapping optional value in annotation popover

---

Zotero/Controllers/Database/Requests/StoreGroupDbRequest.swift

Fixes missing permissions for owners, when only admins have metadata or file editing.

Fix group owner permissions

---

Zotero.xcodeproj/project.pbxproj
Zotero/Models/AnnotationsConfig.swift
Zotero/Scenes/Detail/Annotation Popover/Views/AnnotationEditViewController.swift
Zotero/Scenes/Detail/Annotation Popover/Views/TextContentEditCell.swift
Zotero/Scenes/Detail/Annotation Popover/Views/TextContentEditCell.xib
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Also fixed content editing for underline annotation

Enabled text & underline annotations

---

Zotero/Scenes/Detail/PDF/Views/AnnotationToolbarViewController.swift

Take into account annotation tool button spacing for layout

---

Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

* Uses correct indexes if there are invalid annotations
* Improves free text annotation validation

Fix reader action handler update from database

---

Zotero/Assets/en.lproj/Localizable.strings
Zotero/Controllers/Sync/SyncController.swift
Zotero/Extensions/Localizable.swift
Zotero/Models/ConflictResolution.swift
Zotero/Scenes/AppCoordinator.swift

Discussed in https://github.com/zotero/zotero-android/issues/152

Fix incorrect group permissions handling

---

Zotero.xcodeproj/project.pbxproj
Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Controllers/Attachment Downloader/RemoteAttachmentDownloader.swift
Zotero/Controllers/Controllers.swift
Zotero/Controllers/Database/Requests/CreateAttachmentDbRequest.swift
Zotero/Controllers/IdentifierLookupController.swift
Zotero/Controllers/Sync/SyncActions/UploadFixSyncAction.swift
Zotero/Controllers/ZoteroURIConverter.swift
Zotero/Models/AnnotationPreview.swift
Zotero/Models/Attachment.swift
Zotero/Models/CitationMetadata.swift
Zotero/Scenes/AppCoordinator.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/PDF/Models/PDFReaderState.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/General/Models/NoteEditorAction.swift
Zotero/Scenes/General/Models/NoteEditorState.swift
Zotero/Scenes/General/NoteEditorCoordinator.swift
Zotero/Scenes/General/ViewModels/NoteEditorActionHandler.swift
Zotero/Scenes/General/Views/NoteEditorViewController.swift

Implemented note editor actions for annotations/citations. Small refactoring included.

Note editor improvements

---

Zotero/Scenes/Detail/ItemDetail/Views/ItemDetailViewController.swift

Fixed bug when attachment would be disabled after opening with navbar button

---

Zotero/Controllers/WebDAV/WebDavPropParserDelegate.swift

Fixed parsing of prop files with whitespaces

---

Zotero/Controllers/AnnotationPreviewController.swift
Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift

Allow rendering of document annotations

---

Zotero.xcodeproj/project.pbxproj
Zotero.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Zotero/Scenes/AppCoordinator.swift
Zotero/Scenes/Detail/PDF/PDFCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFSidebarViewController.swift
Zotero/Scenes/General/Views/TagPickerViewController.swift

* Drops support for iOS 15
* Updates PSPDFKit/PSPDFKit-SP to 14.3.0
* Removes unnecessary code

Drop support for iOS 15

---

Zotero/Scenes/Master/Collections/Views/ExpandableCollectionsCollectionViewHandler.swift

Some sporadic crashes still appear in this function. Haven't reproduced it yet. These changes may the least help us further pinpoint the issue.

Improve ExpandableCollectionsCollectionViewHandler update

---

Zotero.xcodeproj/project.pbxproj

Update realm-swift location URL

Update SPM dependencies

---

Zotero/Controllers/IdleTimerController.swift

Changed idle timer setting to 5 minutes

---

Zotero/Controllers/IdentifierLookupController.swift
Zotero/Controllers/Web View Handling/LookupWebViewHandler.swift
Zotero/Controllers/Web View Handling/WebViewHandler.swift

Some improvements to facilitate reuse of LookupWebViewHandler for retrieving metadata.

Improve lookup

---

Zotero/Scenes/Detail/PDF/Views/PDFAnnotationsViewController.swift

Fixed regression in annotations datasource update

---

Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Hide sidebar separator line in PDF reader

---

Zotero/Controllers/Controllers.swift
Zotero/Controllers/Files/FileStorage.swift

I'm working on speech feature for document readers and when adding new controller I decided to clean up the Controllers wrapper.

Controllers refactoring

---

ZShare/Base.lproj/MainInterface.storyboard
Zotero/Scenes/General/Views/ReaderSettingsSegmentedCell.swift
Zotero/Scenes/General/Views/ReaderSettingsSegmentedCellContentView.swift
Zotero/Scenes/General/Views/ReaderSettingsSegmentedCellContentView.xib
Zotero/Scenes/General/Views/ReaderSettingsViewController.swift

When title is getting truncated due to segmented control being too be, it's converted to button with drop-down menu.

Fix reader setting title truncation

---

Zotero/Controllers/Controllers.swift

Fixed controllers initialization flow

---

Zotero/Controllers/Controllers.swift

Fixes https://forums.zotero.org/discussion/123248/synchronization-error

Re-apply existing child item fix

---

Zotero/Scenes/Master/Settings/Sync/Models/SyncSettingsAction.swift
Zotero/Scenes/Master/Settings/Sync/ViewModels/SyncSettingsActionHandler.swift
Zotero/Scenes/Master/Settings/Sync/Views/SyncSettingsView.swift

Trim sync settings account URL on dismissal and verification

---

Zotero/Info.plist
Zotero/Scenes/Detail/DetailCoordinator.swift

Added background audio support

---

.swiftlint.yml
Zotero.xcodeproj/project.pbxproj
ci_scripts/ci_pre_xcodebuild.sh
scripts/bundle_note_editor.sh
scripts/bundle_pdf_worker.sh
scripts/bundle_reader.sh

Using cached builds for `reader` and `pdf-worker` so far. 
`note-editor` hasn't cause any issues when buildging with Xcode cloud, but will also change this when iOS builds become available in our cache.

Use prebuilt npm

---

ZShare/View Controllers/ShareViewController.swift
Zotero/Controllers/Controllers.swift
Zotero/Controllers/Files/FileStorage.swift
Zotero/Controllers/PDFWorkerController.swift
Zotero/Controllers/TranslatorsAndStylesController.swift
Zotero/Controllers/Web View Handling/PDFWorkerWebViewHandler.swift
Zotero/Controllers/Web View Handling/WebViewHandler.swift
Zotero/Controllers/Web View Handling/worker.html
Zotero/Models/File.swift
Zotero/Models/Files.swift
Zotero/Scenes/Detail/SingleCitation/Views/SingleCitationViewController.swift
ZoteroTests/PDFWorkerControllerSpec.swift

* Fixes WebViewHandler related memory leaks.
* Copies PDF worker files along with PDF file to temporary directory, per PDF work.
* Fixes Files protocol assumptions, when a file exists without an extension.

Fix PDF worker

---

ZShare/Assets/translation/lookup.js
Zotero/Controllers/IdentifierLookupController.swift
Zotero/Controllers/RecognizerController.swift
Zotero/Controllers/TranslatorsAndStylesController.swift
Zotero/Controllers/Web View Handling/LookupWebViewHandler.swift

Limits translators loaded for recognizer lookup, only to those of search type, as recognizer would only lookup arxiv, doi, or isbn identifiers.

Improve recognizer

---

Zotero/Controllers/Database/RealmDbStorage.swift
Zotero/Controllers/Database/Requests/ReadAllAttachmentsFromCollectionDbRequest.swift
Zotero/Controllers/Database/Requests/ReadFilteredTagsDbRequest.swift
Zotero/Controllers/Database/Requests/ReadItemsDbRequest.swift
Zotero/Extensions/UserDefault+Extensions.swift
Zotero/Models/Defaults.swift
Zotero/Models/Notifications.swift
Zotero/Scenes/Detail/Items/Models/ItemsAction.swift
Zotero/Scenes/Detail/Items/ViewModels/ItemsActionHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift

- Presented tags take into account show items from subcollections setting.
- Items view controller observers the setting and updates its results.
Issue reported in this forum [post](https://forums.zotero.org/discussion/124362/ios-app-tags-not-showing-from-subcollections)

Improve show items from subcollections

---

ZShare/ViewModels/ExtensionViewModel.swift
Zotero/Controllers/Attachment Downloader/AttachmentDownloader.swift
Zotero/Controllers/CustomURLController.swift
Zotero/Controllers/OpenItemsController.swift
Zotero/Extensions/NSUserActivity+Activities.swift
Zotero/Models/Defaults.swift
Zotero/SceneDelegate.swift
Zotero/Scenes/AppCoordinator.swift
Zotero/Scenes/Detail/DetailCoordinator.swift
Zotero/Scenes/Detail/HTML:EPUB/Views/HtmlEpubReaderViewController.swift
Zotero/Scenes/Detail/Lookup/LookupCoordinator.swift
Zotero/Scenes/Detail/PDF/Views/PDFPlainReaderViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift
Zotero/Scenes/Detail/ReaderCoordinator.swift
Zotero/Scenes/Main/Views/MainViewController.swift
Zotero/Scenes/Master/Libraries/Views/LibrariesViewController.swift
Zotero/Scenes/Master/MasterCoordinator.swift

* Fixes several edge cases when opening a URL for item selection or presentation in the reader
* Adds support for opening URLS for HTML snapshot & ePub items
(Also streamlines some HTML/ePub cases that will be used to rebase multiple open items)

Improve opening URLs

---

Zotero/Scenes/Master/TagFiltering/Models/TagFilterAction.swift
Zotero/Scenes/Master/TagFiltering/ViewModels/TagFilterActionHandler.swift

Potential fix for this reported [bug](https://forums.zotero.org/discussion/124960/ios-crash-report-683821126)

Improve TagFilterActionHandler

---

Zotero/Controllers/Citation/CitationController.swift
Zotero/Controllers/DragDropController.swift
Zotero/Scenes/Detail/Items/Views/ItemsTableViewHandler.swift
Zotero/Scenes/Detail/Items/Views/ItemsViewController.swift
Zotero/Scenes/Detail/Trash/Views/TrashViewController.swift
Zotero/Scenes/Master/Collections/Views/ExpandableCollectionsCollectionViewHandler.swift
Zotero/Scenes/Master/TagFiltering/Views/TagFilterViewController.swift

* Dropping items in other apps copies their citation in HTML or plain text format.
* Allows drag of multiple items from the same library. (
* Fixes drop on tags that applies tag on dropped items.

Improve drag and drop items

---

Zotero/Scenes/Detail/HTML:EPUB/Views/HtmlEpubDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFDocumentViewController.swift
Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift

Make readers completely full screen

---

Zotero/Controllers/Debugging/ApiLogger.swift

Added underlying `AFError` into the log to know what's actually going on.

Improved API error logging
